name: Build Xamarin.Android app

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.10 --android=10.2

    - name: Setup .NET Core SDK 7.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Install dependencies
      run: nuget restore ${{github.workspace}}/src/MarvelHeroes.sln

    - name: Build
      run: msbuild ${{github.workspace}}/src/MarvelHeroes/MarvelHeroes.Android.csproj /t:PackageForAndroid /p:Configuration=Debug