name: Build iOS app

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --ios=15.0
    
    - name: Set default Xcode 14.3
      run: |
        XCODE_ROOT=/Applications/Xcode_14.3.app
        echo "MD_APPLE_SDK_ROOT=$XCODE_ROOT" >> $GITHUB_ENV
        sudo xcode-select -s $XCODE_ROOT

    - name: Setup .NET Core SDK 7.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Install dependencies
      run: nuget restore ${{github.workspace}}/src/MarvelHeroes.sln

    - name: Build
      run: msbuild ${{github.workspace}}/src/MarvelHeroes/MarvelHeroes.iOS.csproj /p:Configuration=Debug /p:Platform=iPhoneSimulator /t:Rebuild